export const service = {
  serviceId: "AFXasw1SrHauUGcMI0BA",
  project: {
    projectId: "oQZjvI2L8iLP5hFgORzi",
    title: "MAIN DEV",
    logoUrl:
      "https://storage.googleapis.com/timerise-dev.appspot.com/uploads/oQZjvI2L8iLP5hFgORzi/42099bd4-513c-41fd-9909-38ccb3b68e62.png",
    theme: "DARK" as const,
    defaultLocale: "en-PL",
    localTimeZone: "Europe/Warsaw",
  },
  title: "event single",
  description: "",
  price: 0,
  promoPrice: 0,
  currency: "EUR",
  locations: [],
  hostedBy: "host",
  dateTimeTo: "2023-08-25T17:00:00.000Z",
  dateTimeFrom: "2023-08-20T09:00:00.000Z",
  images: [],
  media: [],
  hosts: [],
  viewConfig: {
    bookingStatus: {
      ACCEPTED: {
        actions: {
          calendar: true,
          cancel: true,
          hide: null,
          pay: null,
          qr: false,
          reschedule: false,
          service: true,
          spaces: true,
        },
        description:
          "Thank you for booking our service. We sent a confirmation message to the email address provided. There you will find all the necessary booking details.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/ok.png",
        title: "Booking accepted!",
      },
      CANCELED: {
        actions: {
          cancel: null,
          calendar: null,
          hide: null,
          pay: null,
          qr: null,
          reschedule: null,
          service: true,
          spaces: null,
        },
        description:
          "Booking for this service has been canceled. We have sent a confirmation of this operation to the email address provided.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/error.png",
        title: "Booking canceled!",
      },
      CONFIRMED: {
        actions: null,
        description:
          "Thank you for booking our service. We sent a confirmation message to the email address provided. There you will find all the necessary booking details.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/ok.png",
        title: "Booking confirmed!",
      },
      NEW: {
        actions: {
          calendar: false,
          cancel: true,
          hide: false,
          pay: false,
          qr: false,
          reschedule: null,
          service: true,
          spaces: null,
        },
        description:
          "We sent a message to the email address/phone number provided. Use the link inside to confirm the booking of the service. The link will be valid for 10 minutes.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/inbox.png",
        title: "Check your inbox",
      },
      REJECTED: {
        actions: {
          calendar: null,
          cancel: null,
          hide: null,
          pay: null,
          qr: null,
          reschedule: null,
          service: true,
          spaces: null,
        },
        description:
          "Booking for this service has been canceled. We have sent a confirmation of this operation to the email address provided.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/error.png",
        title: "Booking rejected!",
      },
    },
    paymentStatus: {
      CANCELED: {
        actions: {
          calendar: null,
          cancel: null,
          hide: true,
          pay: null,
          qr: null,
          service: null,
        },
        description: "statusDescription",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/error.png",
        title: "payment cancel",
      },
      NEW: {
        actions: {
          calendar: false,
          cancel: true,
          hide: false,
          pay: true,
          qr: false,
          service: true,
        },
        description:
          "Please make the payment within 60 minutes. No payment will result in cancellation of the reservation.",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/payment.png",
        title: "Waiting for payment",
      },
      PROCESSING: {
        actions: null,
        description: "statusDescription",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/payment.png",
        title: "payment",
      },
      SUCCEEDED: {
        actions: null,
        description: "statusDescription",
        details: true,
        iconUrl: "https://cdn.timerise.io/booking-page/icons/ok.png",
        title: "payment ok",
      },
    },
    displayType: "LIST",
    days: {
      duration: false,
      maxSelect: null,
      minSelect: null,
      multiSelect: false,
      quantity: false,
    },
    list: {
      duration: false,
      maxSelect: null,
      minSelect: null,
      multiSelect: false,
      quantity: true,
      showTime: true,
    },
    calendar: {
      maxRange: "P8D",
      maxSelect: null,
      minRange: "P1D",
      minSelect: null,
      multiSelect: false,
      rangeSelect: true,
      quantity: true,
    },
  },
  paymentProviders: ["OFFLINE"],
  formFields: [
    {
      fieldId: "SYSTEM_FULL_NAME",
      fieldType: "SYSTEM_FULL_NAME",
      required: true,
      label: "Full name",
      order: 0,
      width: 50,
      placeholder: "",
    },
    {
      fieldId: "SYSTEM_EMAIL_ADDRESS",
      fieldType: "SYSTEM_EMAIL_ADDRESS",
      required: true,
      label: "E-mail",
      order: 1,
      width: 50,
      placeholder: null,
    },
  ],
};
